version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - /home/oliver/docker/redis.conf:/usr/local/etc/redis/redis.conf

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - /home/oliver/docker/rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=kidsnote
      - RABBITMQ_DEFAULT_PASS=kidsnote
      - RABBITMQ_DEFAULT_VHOST=default

  db:
    image: mariadb:latest
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: db
    ports:
      - "33306:3306"
    volumes:
      - /home/oliver/docker/db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1

  worker:
    image: dockerkrane:latest
    command: tail -f /dev/null
    container_name: worker
    volumes:
      - /home/oliver/docker/db_data/conf.d/silver_bullet:/etc/mysql/conf.d/silver_bullet
    links:
      - db:db.docker
      - redis:redis.docker
      - rabbitmq:rabbitmq.docker
